# Generated by Django 4.1.7 on 2023-03-28 10:36

from django.db import migrations, models
import main.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_user', '0002_user_posts_liked_alter_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.user.models.user_directory_path),
        ),
    ]
