# Generated by Django 4.1.7 on 2023-03-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='main_post',
        ),
    ]
